/* tslint:disable */
import { CollateralsDto } from './collaterals-dto';
import { GuarantorsDto } from './guarantors-dto';
import { MarketMakersDto } from './market-makers-dto';
import { UnderwritersDto } from './underwriters-dto';

export interface BourseInstrumentDetailsDto {
    account?: string;
    bankId?: number;
    bankName?: string;
    basePrice?: number;
    callRate?: number;
    callable?: number;
    cancellationDate?: string;
    collaterals?: Array<CollateralsDto>;
    contractSize?: number;
    convertible?: number;
    currency?: string;
    embeded?: number;
    etfTypeId?: number;
    etfTypeName?: string;
    exerciseRate?: number;
    guarantors?: Array<GuarantorsDto>;
    id: number;
    issueDate?: string;
    issueDateId?: number;
    issueEndDate?: string;
    issueStartDate?: string;
    issuelicenseId?: number;
    issuelicenseName?: string;
    issuerGoalId?: number;
    issuerGoalName?: string;
    issuerId?: number;
    issuerName?: string;
    margin?: string;
    marketMakers?: Array<MarketMakersDto>;
    marketMakingRate?: number;
    maturityDate?: string;
    name?: string;
    nationalId?: string;
    par?: number;
    paymentDay?: string;
    paymentPeriod?: number;
    putRate?: number;
    rate?: number;
    registerNumber?: number;
    sponsor?: string;
    ticker: string;
    type?: number;
    underlyingAsset?: string;
    underwriters?: Array<UnderwritersDto>;
    value?: string;
    volume?: string;
}
