export const MarketMakingForm = {
    contractBaseInfo: '',
    securityType: '',
    symbol: '',
    issuePermission: '',
    tradingMarket: '',
    executiveBank: '',
    brockerDealer: '',
    securityVolume: '',
    securityCounts: '',
    securityParValue: '',
    ipoDateStart: '',
    ipoDateEnd: '',
    maturityDate: '',
    securityLifecycleFreq: '',
    nominalRate: '',
    profitPaymentFreq: '',
    dailyMinimumCommittedPercent: '',
    dailyMinimumCommittedCount: '',
    dailyExchangeMinimumCommittedPercent: '',
    dailyExchangeMinimumCommittedCount: '',
    syndicateMembersCount: '',
    dailySyndicateCommittedSumAmount: '',
    firstDateMarketMakingFees: '',
    marketMakingFeesFreq: '',
    percentageSalesDeductions: '',
    defaultsPossibleDamagesPercent: '',
    defaultsPossibleDamagesAmount: '',

    marketMakingFeesCounts: '',
    marketMakingFeesConsiderationFreq: '',
    marketMakingFeesConsiderationRate: '',
    marketMakingDelinquencyGracePeriod: '',
    tamadonPettyCashAmount: '',
    tamadonPettyCashPercent: '',
    receiptFirstMarketMakingDate: '',
    pettyCashFreq: '',
    pettyCashCounts: '',
    pettyCashRecievingBankAccount: '',
    pettyCashRecievingBankName: '',
    pettyCashRecievingBranchName: '',

    pettyCashDelinquencyConsiderationFreq: '',
    pettyCashDelinquencyConsiderationRate: '',
    pettyCashDelinquencyGracePeriod: '',
    pettyCashReceivingInfo: '', //form

    pettyCashPayingBackDate: '',
    pettyCashPayingBackFreq: '',
    pettyCashPayingBachCounts: '',

    pettyCashPayingBackDelinquencyConsiderationFreq: '',
    pettyCashPayingBackDelinquencyConsiderationRate: '',
    pettyCashPayingBackDelinquencyGracePeriod: '',
    pettyCashPayingBackInfo: '', //form
    salafPutOptionRate: '',
    salafCallOptionRate: '',
    salafMarketMakingRate: '',
    marketmakingType: '',
    guarantorInfo: '',
    securityName: '',
};

export const UnderWritingForm = {
    securityType: '',
    symbol: '',
    issuePermission: '',
    tradingMarket: '',
    executiveBank: '',
    brockerDealer: '',
    securityVolume: '',
    securityCounts: '',
    securityParValue: '',
    ipoDateStart: '',
    ipoDateEnd: '',
    maturityDate: '',
    securityLifecycleFreq: '',
    nominalRate: '',
    profitPaymentFreq: '',
    dailyMinimumCommittedPercent: '',
    dailyMinimumCommittedCount: '',
    dailyExchangeMinimumCommittedPercent: '',
    dailyExchangeMinimumCommittedCount: '',
    syndicateMembersCount: '',
    dailySyndicateCommittedSumAmount: '',
    firstDateMarketMakingFees: '',
    marketMakingFeesFreq: '',
    percentageSalesDeductions: '',
    defaultsPossibleDamagesPercent: '',
    defaultsPossibleDamagesAmount: '',

    tamadonSyndicateCommittedPercent: '',

    unpurchasedSecuritiesInIpoPercent: '',
    percentagePurchasedUnpurchasedBondsIpo: '',
    NumberPurchasedUnpurchasedBondsIpo: '',
    unitPricePurchasedUnpurchasedBondsIpo: '',
    underWritingConsiderationFreq: '',
    underWritingConsiderationRate: '',
    underWritingFee: '',
    marketMakingFeesReceivingInfo: '',
    maximumPurchasedBondsIssuedDuringIpo: '',
    minimumPurchasePrice: '',
    maximumPurchasePrice: '',
    pettyCashDelinquencyConsiderationFreq: '',
    pettyCashDelinquencyConsiderationRate: '',
};
export const MarketMakingAndUnderWritingForm = {
    securityType: '',
    symbol: '',
    issuePermission: '',
    tradingMarket: '',
    executiveBank: '',
    brockerDealer: '',
    securityVolume: '',
    securityCounts: '',
    securityParValue: '',
    ipoDateStart: '',
    ipoDateEnd: '',
    maturityDate: '',
    securityLifecycleFreq: '',
    nominalRate: '',
    profitPaymentFreq: '',
    dailyMinimumCommittedPercent: '',
    dailyMinimumCommittedCount: '',
    dailyExchangeMinimumCommittedPercent: '',
    dailyExchangeMinimumCommittedCount: '',
    syndicateMembersCount: '',
    dailySyndicateCommittedSumAmount: '',
    firstDateMarketMakingFees: '',
    marketMakingFeesFreq: '',
    percentageSalesDeductions: '',
    defaultsPossibleDamagesPercent: '',
    defaultsPossibleDamagesAmount: '',

    marketMakingFeesCounts: '',
    marketMakingFeesConsiderationFreq: '',
    marketMakingFeesConsiderationRate: '',
    marketMakingDelinquencyGracePeriod: '',
    tamadonPettyCashAmount: '',
    tamadonPettyCashPercent: '',
    receiptFirstMarketMakingDate: '',
    pettyCashFreq: '',
    pettyCashCounts: '',
    pettyCashRecievingBankAccount: '',
    pettyCashRecievingBankName: '',
    pettyCashRecievingBranchName: '',

    pettyCashDelinquencyConsiderationFreq: '',
    pettyCashDelinquencyConsiderationRate: '',
    pettyCashDelinquencyGracePeriod: '',
    pettyCashReceivingInfo: '', //form

    pettyCashPayingBackDate: '',
    pettyCashPayingBackFreq: '',
    pettyCashPayingBachCounts: '',

    pettyCashPayingBackDelinquencyConsiderationFreq: '',
    pettyCashPayingBackDelinquencyConsiderationRate: '',
    pettyCashPayingBackDelinquencyGracePeriod: '',
    pettyCashPayingBackInfo: '', //form
    salafPutOptionRate: '',
    salafCallOptionRate: '',
    salafMarketMakingRate: '',
    marketmakingType: '',
    guarantorInfo: '',
    securityName: '',

    tamadonSyndicateCommittedPercent: '',

    unpurchasedSecuritiesInIpoPercent: '',
    percentagePurchasedUnpurchasedBondsIpo: '',
    NumberPurchasedUnpurchasedBondsIpo: '',
    unitPricePurchasedUnpurchasedBondsIpo: '',
    underWritingConsiderationFreq: '',
    underWritingConsiderationRate: '',
    underWritingFee: '',
    marketMakingFeesReceivingInfo: '',
    maximumPurchasedBondsIssuedDuringIpo: '',
    minimumPurchasePrice: '',
    maximumPurchasePrice: '',
};

export const ValuationForm = {
    projectOrCorporateUnderValuation: '',
    prepaymentReceivingDate: '',
    relatedDocumentsDeliveredDate: '',
    contractAmount: 0,
    paymentCounts: 0,
    feeCashDelinquencyConsiderationFreq: 0,
    feeCashDelinquencyConsiderationRate: 0,
    feeCashDelinquencyGracePeriod: 0,
};

export const AdvisoryForm = {
    securityType: 0,
    securityIssuedAmount: 0,
    securityIssuedCounts: 0,
    securityParValue: 0,
    prepaymentReceivingDate: '',
    relatedDocumentsDeliveredDate: '',
    contractFeeRate: 0,
    contractFeeAmount: 0,
    paymentCounts: 0,
    successAmount: 0,
    successAmountReceivingDate: '',
    contractEndingReason: 0,
    contractEndingReasonExplanation: '',
    feeCashDelinquencyConsiderationFreq: 0,
    feeCashDelinquencyConsiderationRate: 0,
    feeCashDelinquencyGracePeriod: 0,
};

export const financingAdvisoryForm = {
    securityType: 0,
    financingAmount: 0,
    financingFeesRate: 0,
    financingFeesAmount: 0,
    marketingAndSellFeesRate: 0,
    financingFeesReceivingDate: '',
    contractEndingReason: 0,
    contractEndingReasonExplanation: '',
    feeCashDelinquencyConsiderationFreq: 0,
    feeCashDelinquencyConsiderationRate: 0,
    feeCashDelinquencyGracePeriod: 0,
};

export const exlcusivelyAssetManagementForm = {
    investorAssetsVolumeDeliveringToAssetManager: 0,
    investorAssetsDeliveringDateToAssetManager: '',
    investorRealAssetsVolumeDeliveringToAssetManager: 0,
    investorCashDeliveringToAssetManager: 0,
    investorCashDeliveringDateToAssetManager: 0,
    investorRealCashDeliveringToAssetManager: 0,
    completlyAssetDeliveringPeriod: 0,
    completlyAssetDeliveringDate: '',
    investorAssetAmountInDeliveringDateToAssetManager: 0,
    investorCashInDeliveringDateToAssetManager: 0,
    stockFixedFeesRateFreq: 0,
    stockFixedFeesRateCal: 0,
    securityFixedFeesRateFreq: 0,
    securityFixedFeesRateCal: 0,
    settlementFeesFreq: 0,
    portfolioAssetsPayingBankAccount: 0,
    portfolioAssetsPayingBankName: '',
    portfolioAssetsPayingBranchName: '',
};
